//! Settings handlers - Telegram OTP linking (Member 4's extended feature).
//!
//! Routes:
//!   GET  /settings/telegram          guide + deep link, linked status, auto-refresh
//!   POST /settings/telegram/unlink   OTP-gated unlink
//!   POST /settings/email|password    OTP-gated profile changes

use actix_web::{web, HttpResponse};
use askama::Template;
use rand::Rng;

use crate::errors::AppError;
use crate::middleware::auth::CurrentUser;
use crate::models::user::Role;
use crate::services::action_otp_service::ActionOtpService;
use crate::services::auth_service::AuthService;
use crate::state::AppState;
use crate::view::{LayoutCtx, OtpConfirmPage};

pub fn routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/settings")
            .route("/telegram", web::get().to(telegram_page))
            .route("/telegram/status", web::get().to(telegram_status))
            .route("/telegram/unlink", web::post().to(telegram_unlink))
            .route("/telegram/unlink/confirm", web::post().to(telegram_unlink_confirm))
            .route("/telegram/unlink/cancel", web::post().to(telegram_unlink_cancel))
            .route("/email", web::post().to(email_change))
            .route("/email/confirm", web::post().to(email_change_confirm))
            .route("/password", web::post().to(password_change))
            .route("/password/confirm", web::post().to(password_change_confirm)),
    );
}

#[derive(Template)]
#[template(path = "settings/telegram.html")]
struct TelegramTemplate {
    layout: LayoutCtx,
    /// Server has a bot token configured at all.
    enabled: bool,
    /// This user already linked their Telegram.
    linked: bool,
    /// Deep link that opens the bot with a single-use code (only when unlinked).
    link_url: Option<String>,
    /// A bot-requested unlink waiting out its 24h window (cancellable here).
    pending_unlink: Option<chrono::DateTime<chrono::Utc>>,
}

/// Staff have no bank accounts, no transfers, and no OTP flows - the page is
/// customers-only, exactly as the access rules demand.
fn customers_only(user: &CurrentUser) -> Result<(), AppError> {
    if user.role != Role::Customer {
        return Err(AppError::Forbidden);
    }
    Ok(())
}

async fn telegram_page(
    state: web::Data<AppState>,
    user: CurrentUser,
) -> Result<HttpResponse, AppError> {
    customers_only(&user)?;
    let enabled = state.telegram_bot.is_some();

    let row: (Option<i64>, Option<chrono::DateTime<chrono::Utc>>) = sqlx::query_as(
        r#"SELECT telegram_chat_id, telegram_unlink_at FROM users WHERE id = $1"#,
    )
    .bind(user.id)
    .fetch_one(&state.db)
    .await?;
    let linked = row.0.is_some();
    let pending_unlink = row.1;

    // Mint a fresh single-use code on every visit (overwrites an unused one -
    // harmless, and it means a stale link can simply be regenerated by reload).
    let link_url = match (&state.telegram_bot, linked) {
        (Some(bot), false) => {
            let code: String = {
                const CHARS: &[u8] = b"abcdefghijklmnopqrstuvwxyz0123456789";
                let mut rng = rand::thread_rng();
                (0..32).map(|_| CHARS[rng.gen_range(0..CHARS.len())] as char).collect()
            };
            sqlx::query(r#"UPDATE users SET telegram_link_code = $1 WHERE id = $2"#)
                .bind(&code)
                .bind(user.id)
                .execute(&state.db)
                .await?;
            Some(format!("https://t.me/{bot}?start={code}"))
        }
        _ => None,
    };

    let body = TelegramTemplate {
        layout: LayoutCtx::from_user(Some(&user)),
        enabled,
        linked,
        link_url,
        pending_unlink,
    }
    .render()
    .map_err(|e| AppError::Internal(anyhow::anyhow!("settings template: {e}")))?;

    Ok(HttpResponse::Ok()
        .content_type("text/html; charset=utf-8")
        .body(body))
}

#[derive(serde::Deserialize)]
struct ActionConfirmForm {
    action_id: i64,
    otp: String,
}

/// Profile changes are OTP-gated too: unlinking sends one last code to the
/// (still linked) Telegram before the link is dropped.
async fn telegram_unlink(
    otp_svc: web::Data<dyn ActionOtpService>,
    user: CurrentUser,
) -> Result<HttpResponse, AppError> {
    customers_only(&user)?;
    let challenge = otp_svc
        .begin(user.id, "telegram.unlink", serde_json::json!({}))
        .await?;

    let body = OtpConfirmPage {
        layout: LayoutCtx::from_user(Some(&user)),
        title: "Confirm Telegram unlink".into(),
        summary: vec![(
            "Effect".into(),
            "codes appear on screen again".into(),
        )],
        action_url: "/settings/telegram/unlink/confirm".into(),
        cancel_url: "/settings/telegram".into(),
        action_id: challenge.action_id,
        demo_otp: if challenge.delivered { None } else { Some(challenge.otp) },
        error: None,
    }
    .render()
    .map_err(|e| AppError::Internal(anyhow::anyhow!("settings template: {e}")))?;
    Ok(HttpResponse::Ok()
        .content_type("text/html; charset=utf-8")
        .body(body))
}

async fn telegram_unlink_confirm(
    form: web::Form<ActionConfirmForm>,
    otp_svc: web::Data<dyn ActionOtpService>,
    state: web::Data<AppState>,
    user: CurrentUser,
) -> Result<HttpResponse, AppError> {
    customers_only(&user)?;
    if let Err(e) = otp_svc
        .verify(user.id, form.action_id, "telegram.unlink", &form.otp)
        .await
    {
        return match e {
            AppError::BadRequest(msg) => render_otp_retry(
                &user,
                "Confirm Telegram unlink",
                "/settings/telegram/unlink/confirm",
                form.action_id,
                msg,
            ),
            other => Err(other),
        };
    }

    sqlx::query(
        r#"UPDATE users SET telegram_chat_id = NULL, telegram_link_code = NULL WHERE id = $1"#,
    )
    .bind(user.id)
    .execute(&state.db)
    .await?;

    Ok(HttpResponse::Found()
        .insert_header(("Location", "/settings/telegram"))
        .finish())
}

// ── Link-status poll (the guide page auto-refreshes on this) ─────────

async fn telegram_status(
    state: web::Data<AppState>,
    user: CurrentUser,
) -> Result<HttpResponse, AppError> {
    customers_only(&user)?;
    let linked: Option<bool> =
        sqlx::query_scalar::<_, bool>(r#"SELECT telegram_chat_id IS NOT NULL FROM users WHERE id = $1"#)
            .bind(user.id)
            .fetch_optional(&state.db)
            .await?;
    Ok(HttpResponse::Ok().json(serde_json::json!({ "linked": linked.unwrap_or(false) })))
}

// ── Profile changes (OTP-gated): email & password ────────────────────

#[derive(serde::Deserialize)]
struct EmailForm {
    new_email: String,
}

async fn email_change(
    form: web::Form<EmailForm>,
    otp_svc: web::Data<dyn ActionOtpService>,
    user: CurrentUser,
) -> Result<HttpResponse, AppError> {
    customers_only(&user)?;
    let new_email = form.new_email.trim().to_string();
    if !new_email.contains('@') || new_email.len() < 5 {
        return Err(AppError::BadRequest("that doesn't look like an email address".into()));
    }
    let challenge = otp_svc
        .begin(user.id, "profile.email", serde_json::json!({ "email": new_email }))
        .await?;
    render_confirm(
        &user,
        "Confirm email change",
        vec![("New email".into(), new_email)],
        "/settings/email/confirm",
        challenge,
    )
}

async fn email_change_confirm(
    form: web::Form<ActionConfirmForm>,
    otp_svc: web::Data<dyn ActionOtpService>,
    auth_svc: web::Data<dyn AuthService>,
    user: CurrentUser,
) -> Result<HttpResponse, AppError> {
    customers_only(&user)?;
    let payload = match otp_svc
        .verify(user.id, form.action_id, "profile.email", &form.otp)
        .await
    {
        Ok(p) => p,
        Err(AppError::BadRequest(msg)) => {
            return render_otp_retry(
                &user,
                "Confirm email change",
                "/settings/email/confirm",
                form.action_id,
                msg,
            )
        }
        Err(other) => return Err(other),
    };
    let email = payload["email"]
        .as_str()
        .ok_or_else(|| AppError::Internal(anyhow::anyhow!("bad profile.email payload")))?;
    auth_svc.change_email(user.id, email).await?;
    Ok(HttpResponse::Found()
        .insert_header(("Location", "/settings/telegram"))
        .finish())
}

#[derive(serde::Deserialize)]
struct PasswordForm {
    new_password: String,
}

async fn password_change(
    form: web::Form<PasswordForm>,
    otp_svc: web::Data<dyn ActionOtpService>,
    user: CurrentUser,
) -> Result<HttpResponse, AppError> {
    customers_only(&user)?;
    if form.new_password.len() < 8 {
        return Err(AppError::BadRequest("password must be at least 8 characters".into()));
    }
    let challenge = otp_svc
        .begin(
            user.id,
            "profile.password",
            serde_json::json!({ "password": form.new_password }),
        )
        .await?;
    render_confirm(
        &user,
        "Confirm password change",
        vec![("Effect".into(), "your password will be replaced".into())],
        "/settings/password/confirm",
        challenge,
    )
}

async fn password_change_confirm(
    form: web::Form<ActionConfirmForm>,
    otp_svc: web::Data<dyn ActionOtpService>,
    auth_svc: web::Data<dyn AuthService>,
    user: CurrentUser,
) -> Result<HttpResponse, AppError> {
    customers_only(&user)?;
    let payload = match otp_svc
        .verify(user.id, form.action_id, "profile.password", &form.otp)
        .await
    {
        Ok(p) => p,
        Err(AppError::BadRequest(msg)) => {
            return render_otp_retry(
                &user,
                "Confirm password change",
                "/settings/password/confirm",
                form.action_id,
                msg,
            )
        }
        Err(other) => return Err(other),
    };
    let password = payload["password"]
        .as_str()
        .ok_or_else(|| AppError::Internal(anyhow::anyhow!("bad profile.password payload")))?;
    auth_svc.change_password(user.id, password).await?;
    Ok(HttpResponse::Found()
        .insert_header(("Location", "/settings/telegram"))
        .finish())
}

/// Shared renderer for the profile-change OTP pages.
fn render_confirm(
    user: &CurrentUser,
    title: &str,
    summary: Vec<(String, String)>,
    action_url: &str,
    challenge: crate::services::action_otp_service::ActionChallenge,
) -> Result<HttpResponse, AppError> {
    let body = OtpConfirmPage {
        layout: LayoutCtx::from_user(Some(user)),
        title: title.to_string(),
        summary,
        action_url: action_url.to_string(),
        cancel_url: "/settings/telegram".to_string(),
        action_id: challenge.action_id,
        demo_otp: if challenge.delivered { None } else { Some(challenge.otp) },
        error: None,
    }
    .render()
    .map_err(|e| AppError::Internal(anyhow::anyhow!("settings template: {e}")))?;
    Ok(HttpResponse::Ok()
        .content_type("text/html; charset=utf-8")
        .body(body))
}

/// Inline retry: wrong code, action still pending - same page, same action id.
fn render_otp_retry(
    user: &CurrentUser,
    title: &str,
    action_url: &str,
    action_id: i64,
    error: String,
) -> Result<HttpResponse, AppError> {
    let body = OtpConfirmPage {
        layout: LayoutCtx::from_user(Some(user)),
        title: title.to_string(),
        summary: vec![],
        action_url: action_url.to_string(),
        cancel_url: "/settings/telegram".to_string(),
        action_id,
        demo_otp: None,
        error: Some(error),
    }
    .render()
    .map_err(|e| AppError::Internal(anyhow::anyhow!("settings template: {e}")))?;
    Ok(HttpResponse::Ok()
        .content_type("text/html; charset=utf-8")
        .body(body))
}

/// Cancel a bot-scheduled unlink. Requires the website session (password
/// authenticated), which is exactly the channel an attacker inside a stolen
/// Telegram account does NOT have.
async fn telegram_unlink_cancel(
    state: web::Data<AppState>,
    user: CurrentUser,
) -> Result<HttpResponse, AppError> {
    customers_only(&user)?;
    let cancelled = sqlx::query(
        r#"UPDATE users SET telegram_unlink_at = NULL WHERE id = $1 AND telegram_unlink_at IS NOT NULL"#,
    )
    .bind(user.id)
    .execute(&state.db)
    .await?;
    if cancelled.rows_affected() > 0 {
        crate::services::audit_service::notify(
            &state.db,
            user.id,
            "The scheduled Telegram unlink was cancelled. If you didn't request that unlink, change your password now.",
        )
        .await;
        let _ = sqlx::query(
            r#"INSERT INTO audit_log (actor_user_id, event, payload) VALUES ($1, 'telegram.unlink_cancelled', '{}'::jsonb)"#,
        )
        .bind(user.id)
        .execute(&state.db)
        .await;
    }
    Ok(HttpResponse::Found()
        .insert_header(("Location", "/settings/telegram"))
        .finish())
}
