//! Settings handlers — Telegram OTP linking (Member 4's extended feature).
//!
//! Routes:
//!   GET  /settings/telegram         → guide + deep link (or linked status)
//!   POST /settings/telegram/unlink  → drop the link, fall back to on-screen OTP

use actix_web::{web, HttpResponse};
use askama::Template;
use rand::Rng;

use crate::errors::AppError;
use crate::services::action_otp_service::ActionOtpService;
use crate::middleware::auth::CurrentUser;
use crate::state::AppState;
use crate::view::{LayoutCtx, OtpConfirmPage};

pub fn routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/settings")
            .route("/telegram", web::get().to(telegram_page))
            .route("/telegram/unlink", web::post().to(telegram_unlink))
            .route("/telegram/unlink/confirm", web::post().to(telegram_unlink_confirm)),
    );
}

#[derive(Template)]
#[template(path = "settings/telegram.html")]
struct TelegramTemplate {
    layout: LayoutCtx,
    /// Server has a bot token configured at all.
    enabled: bool,
    /// This user already linked their Telegram.
    linked: bool,
    /// Deep link that opens the bot with a single-use code (only when unlinked).
    link_url: Option<String>,
}

async fn telegram_page(
    state: web::Data<AppState>,
    user: CurrentUser,
) -> Result<HttpResponse, AppError> {
    let enabled = state.telegram_bot.is_some();

    let chat_id: Option<i64> =
        sqlx::query_scalar::<_, Option<i64>>(r#"SELECT telegram_chat_id FROM users WHERE id = $1"#)
            .bind(user.id)
            .fetch_one(&state.db)
            .await?;
    let linked = chat_id.is_some();

    // Mint a fresh single-use code on every visit (overwrites an unused one —
    // harmless, and it means a stale link can simply be regenerated by reload).
    let link_url = match (&state.telegram_bot, linked) {
        (Some(bot), false) => {
            let code: String = {
                const CHARS: &[u8] = b"abcdefghijklmnopqrstuvwxyz0123456789";
                let mut rng = rand::thread_rng();
                (0..32).map(|_| CHARS[rng.gen_range(0..CHARS.len())] as char).collect()
            };
            sqlx::query(r#"UPDATE users SET telegram_link_code = $1 WHERE id = $2"#)
                .bind(&code)
                .bind(user.id)
                .execute(&state.db)
                .await?;
            Some(format!("https://t.me/{bot}?start={code}"))
        }
        _ => None,
    };

    let body = TelegramTemplate {
        layout: LayoutCtx::from_user(Some(&user)),
        enabled,
        linked,
        link_url,
    }
    .render()
    .map_err(|e| AppError::Internal(anyhow::anyhow!("settings template: {e}")))?;

    Ok(HttpResponse::Ok()
        .content_type("text/html; charset=utf-8")
        .body(body))
}

#[derive(serde::Deserialize)]
struct ActionConfirmForm {
    action_id: i64,
    otp: String,
}

/// Profile changes are OTP-gated too: unlinking sends one last code to the
/// (still linked) Telegram before the link is dropped.
async fn telegram_unlink(
    otp_svc: web::Data<dyn ActionOtpService>,
    user: CurrentUser,
) -> Result<HttpResponse, AppError> {
    let challenge = otp_svc
        .begin(user.id, "telegram.unlink", serde_json::json!({}))
        .await?;

    let body = OtpConfirmPage {
        layout: LayoutCtx::from_user(Some(&user)),
        title: "Confirm Telegram unlink".into(),
        summary: vec![(
            "Effect".into(),
            "codes appear on screen again".into(),
        )],
        action_url: "/settings/telegram/unlink/confirm".into(),
        cancel_url: "/settings/telegram".into(),
        action_id: challenge.action_id,
        demo_otp: if challenge.delivered { None } else { Some(challenge.otp) },
        error: None,
    }
    .render()
    .map_err(|e| AppError::Internal(anyhow::anyhow!("settings template: {e}")))?;
    Ok(HttpResponse::Ok()
        .content_type("text/html; charset=utf-8")
        .body(body))
}

async fn telegram_unlink_confirm(
    form: web::Form<ActionConfirmForm>,
    otp_svc: web::Data<dyn ActionOtpService>,
    state: web::Data<AppState>,
    user: CurrentUser,
) -> Result<HttpResponse, AppError> {
    otp_svc
        .verify(user.id, form.action_id, "telegram.unlink", &form.otp)
        .await?;

    sqlx::query(
        r#"UPDATE users SET telegram_chat_id = NULL, telegram_link_code = NULL WHERE id = $1"#,
    )
    .bind(user.id)
    .execute(&state.db)
    .await?;

    Ok(HttpResponse::Found()
        .insert_header(("Location", "/settings/telegram"))
        .finish())
}
